item {
  id: 1
  name: "date_of_birth"
  display_name: "date_of_birth"
}
item {
  id: 2
  name: "date_of_expiration"
  display_name: "date_of_expiration"
}
item {
  id: 3
  name: "document_number"
  display_name: "document_number"
}
item {
  id: 4
  name: "given_names"
  display_name: "given_names"
}
item {
  id: 5
  name: "nationality"
  display_name: "nationality"
}
item {
  id: 6
  name: "place_of_birth"
  display_name: "place_of_birth"
}
item {
  id: 7
  name: "sex"
  display_name: "sex"
}
item {
  id: 8
  name: "surname"
  display_name: "surname"
}
